name: CI
on: [pull_request]
jobs:
  lint-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Load cached $HOME/.local
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: dotlocal-${{ runner.os }}-${{ hashFiles('.github/workflows/ci.yml') }}
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: poetry
      - run: poetry install
        name: Install Development Dependencies
      - run: poetry run make lint
        name: Lint
      - run: poetry build
        name: Test poetry build
